name: Deploy to AWS
on: 
  push:
    branches: 
      - deploy-to-ec2

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env
        run: echo "MONGODB_URI=$MONGO_URI" >> .env
      - name: Login to docker hub
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
      - name: Build docker image
        run: docker build -t $DOCKER_USERNAME/wishlist:${GITHUB_SHA::7} .
      - name: Push image to docker hub
        run: docker push $DOCKER_USERNAME/wishlist:${GITHUB_SHA::7}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_USERNAME/wishlist:${GITHUB_SHA::7}
      - name: Delete old container
        run: docker rm -f wishlist-container  
      - name: Run docker container          
        run: docker run -d -p 8080:8080 --name wishlist-container $DOCKER_USERNAME/wishlist:${GITHUB_SHA::7}
    